# Generated by Django 4.2.5 on 2024-10-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=500)),
                ('Occupation', models.CharField(max_length=500)),
                ('UseMobileBankingApps', models.CharField(max_length=500)),
                ('HowLongBeenUsingMobileBankingApplications', models.CharField(max_length=500)),
                ('UsingBankingAppsMakesFinancialManagementMoreEfficient', models.CharField(max_length=500)),
                ('BankingAppsProvideFinancialAdviceThatIFindUseful', models.CharField(max_length=500)),
                ('ItIsImportantThatAIBankingAppsAreAvailableInMyNativeLanguage', models.CharField(max_length=500)),
                ('IWouldBeMoreLikelyToUseAIEnabledMobileBankingIfItInteractedInACulturallyAppropriateManner', models.CharField(max_length=500)),
                ('AIFeaturesSuchAsChatbotsAndAutomatedAlertsInMobileBankingAreEasyToUse', models.CharField(max_length=500)),
                ('SeamlessIntegrationOfAIIntoMobileBankingAppsMakesMeMoreLikelyToUseThem', models.CharField(max_length=500)),
                ('MyCulturalBackgroundInfluencesMyTrustAndUseOfAIEnabledMobileBanking', models.CharField(max_length=500)),
                ('IPreferAIFeaturesThatAreSensitiveToMyCulture', models.CharField(max_length=500)),
                ('ITrustTheSecurityMeasuresInAIEnabledMobileBankingApps', models.CharField(max_length=500)),
                ('PersonalizedServiceInAIEnabledMobileBankingIncreaseMySatisfaction', models.CharField(max_length=500)),
                ('AIEnabledMobileBankingAppearsIntelligentEnoughToHandleComplexTransactions', models.CharField(max_length=500)),
                ('IFeelComfortableInteractingWithAIAsThoughItWereAHumanBankingAssistant', models.CharField(max_length=500)),
                ('PleaseProvideAnyAdditionalCommentsOrSuggestionsRegardingAIEnabledMobileBanking', models.CharField(max_length=500)),
            ],
        ),
    ]
